plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

javafx {
    version = '21'
    modules = ['javafx.controls', 'javafx.fxml']
}

application {
    mainClass = 'org.flightsim.Main'
    applicationDefaultJvmArgs = ["--enable-native-access=ALL-UNNAMED"]
}

compileJava.options.encoding = 'UTF-8'
